#!/bin/bash
# Use > 1 to consume two arguments per pass in the loop (e.g. each
# argument has a corresponding value to go with it).
# Use > 0 to consume one or more arguments per pass in the loop (e.g.
# some arguments don't have a corresponding value to go with it such
# as in the --default example).
# note: if this is set to > 0 the /etc/hosts part is not recognized ( may be a bug )
while [[ $# > 1 ]]
do
key="$1"

case $key in
    --storm.zookeeper.servers)
    ZOOKEEPER_SERVERS="$2"
    shift
    ;;
    --storm.zookeeper.port)
    ZOOKEEPER_PORT="$2"
    shift
    ;;
    --storm.zookeeper.root)
    ZOOKEEPER_ROOT="$2"
    shift
    ;;
    --nimbus.host)
    NIMBUS_HOST="$2"
    shift
    ;;
    --default)
    DEFAULT=YES
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

if [ -z $ZOOKEEPER_SERVERS ]; then
  if [ ! -z $ZOOKEEPER_SERVICE_HOST ]; then
    ZOOKEEPER_SERVERS=$ZOOKEEPER_SERVICE_HOST
  else
    echo "must config --storm.zookeeper.servers! "
    exit 1
  fi
fi
echo "storm.zookeeper.servers:" >> conf/storm.yaml
IFS=,
ary=($ZOOKEEPER_SERVERS)
for idx in "${ary[@]}"
do
echo $idx
echo "- ${idx}" >> conf/storm.yaml
done

if [ ! -z $ZOOKEEPER_PORT ]; then
  echo "storm.zookeeper.port: ${ZOOKEEPER_PORT}" >> conf/storm.yaml
fi
if [ ! -z $ZOOKEEPER_ROOT ]; then
  echo "storm.zookeeper.root: ${ZOOKEEPER_ROOT}" >> conf/storm.yaml
fi
if [ ! -z $NIMBUS_HOST ]; then
  echo "nimbus.host: \"${NIMBUS_HOST}\"" >> conf/storm.yaml
fi
# always set storm.local.hostname
SELF_HOST=$(hostname -I | xargs)
echo "storm.local.hostname: \"${SELF_HOST}\"" >> conf/storm.yaml
